name: Workflow Test

on: [push]

jobs:
  test-execution:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Node.js Configuration
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run Script
      run: |
        echo "Pipeline executada com sucesso!"
        echo "Listando arquivos do reposit√≥rio:"
        ls -la
